### ISSUE TITLE
ge:used is lost

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen#32] opened 2017-05-26 12:06 UTC
When I compare the beta and the dev, it seems that the rendering of `ge:used` is lost. Is this a known bug?

For an example, see http://dev.faustedition.net/documentViewer?faustUri=faust://xml/document/test/test.xml&page=18&view=facsimile_document.

**Comment by thvitt** [comment] 2017-10-30 14:51
same problem as #14

**Comment by wissenbach** [comment] 2017-11-15 15:21
duplicate of #14

**Closed by wissenbach** 2017-11-15 15:21 UTC
Labels: c:diplomatic-rendering
